### ISSUE TITLE
[S3]: Add Storage Class Support

### ISSUE THREAD

**Issue by gencer** [nienbo/cache-buildkite-plugin#15]
S3 supports these storage classes:

- STANDARD (default)
- STANDARD_IA
- ONEZONE_IA
- GLACIER
- DEEP_ARCHIVE
- INTELLIGENT_TIERING _New!_

While Glacier and Deep Archive absolutely not fit to caching mechanism, Between others could be great to support. Especially `ONEZONE_IA` and `INTELLIGENT_TIERING`

```yaml
steps:
  - plugins:
    - gencer/cache#upcoming...:
        backend: s3
        key: "v1-cache-{{ runner.os }}-{{ checksum 'Podfile.lock' }}"
        s3:
          profile: "my-s3-profile"
          bucket: "my-unique-s3-bucket-name"
          compress: true # Create tar.gz instead of .tar (Compressed) Defaults to `false`.
          class: 'ONEZONE_IA' # Defaults to `STANDARD`       <-- HERE
        paths:
          - 'Pods/'
          - 'Rome/'
```

or set by environment:

```
export BUILDKITE_PLUGIN_CACHE_S3_CLASS="ONEZONE_IA"
```
