### ISSUE TITLE
Permission issues when using with Docker + Yarn

### ISSUE THREAD

**Issue by bradbarrow** [nienbo/cache-buildkite-plugin#32]
Hi folks, thanks for the plugin :) 

I'm a bit stuck trying to use this with yarn + the [Buildkite docker plugin](https://github.com/buildkite-plugins/docker-buildkite-plugin)

**First build**

- cache plugin runs
  - finds no cache on S3
- docker plugin runs
  - mounts buildkite agent work dir into container (`node:14`)
  - runs `yarn install` inside the container
- cache plugin runs
  - pushes `node_modules` to S3

**Second build**

- cache plugin runs
  - finds a cache on S3
  - un-tars the cache
  - **ERROR** - the tar can't be un-tarred because the `node_modules` exist on the host already
  - they weren't cleaned up in buildkite checkout step
  - because they are owned by `root`, not the `buildkite-agent` user
  -  because they were created in the docker container

**I have tried:**

- using `docker` plugin's `propagate-uid-gid` setting so that we act as the `buildkite-agent` user in the docker container
  - this has other issues, where yarn can't create it's `~/.cache` dir
- using the `node:14` image's built in `node` user
  -  this has issues on first-run builds because it can't create the `node_modules` file 

My pipeline is pretty straight forward. The second build immediately has trouble untarring the cache because node modules on the host weren't cleaned up due to permission issues. 

```
cache_plugin_config: &cache_plugin_config
  id: gencer-cache-node-modules
  backend: s3
  key: "v1-cache-{{ runner.os }}-{{ checksum 'yarn.lock' }}"
  restore-keys:
    - 'v1-cache-{{ id }}-{{ runner.os }}-'
    - 'v1-cache-{{ id }}-'
  s3:
    bucket: "buildkite-node-modules-cache"
  paths:
    - node_modules

steps:
  - name: ':jest: Test'
    command:
      - "yarn install"
      - "yarn run test"
    plugins:
      - gencer/cache#v2.4.8: *cache_plugin_config
      - docker#v3.8.0:
          image: "node:14"
```
