### ISSUE TITLE
Docker compose build example

### ISSUE THREAD

**Issue by miles-** [nienbo/cache-buildkite-plugin#40]
Thanks for the plugin! I was wondering if there is a working example of using this plugin alongside the [docker-compose](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin) plugin. Specifically, is it possible to use the cache plugin when building an image via the docker-compose plugin?

I see that both docker and docker-compose are [listed in the README](https://github.com/gencer/cache-buildkite-plugin#usage-with-docker), but I wasn't able to find a full example using both the cache plugin and docker-compose. Does the directory that is being cached need to be mounted via a volume in the docker-compose.yml file?

**Comment by gencer** [comment]
Hey @miles- !

To Buildkite works on your files, you already mount the working directory to the Docker Compose, right? So, You are already good to go with cache plugin. Cache will see, archive or unarchive files in your working dir which is already mounted to Docker via Compose.

Honestly, I cannot give more information without knowing more about your use case at the moment. But simply, this will work:

```yaml
ecr: &ecr
  login: true
  account_ids: ${AWS_ACCOUNT}
  region: 'us-east-2'

centos7: &centos7
  run: centos7
  mount-buildkite-agent: true
  config: .buildkite/docker-compose.yml

cache: &cache
  key: 'v1-cache-{{ runner.os }}-qt${Qt5_VER}'
  backend: s3
  s3:
    bucket: caches
  paths:
    - 'opt/${Qt5_VER}'

steps:
  # At some point in `steps` you just `build` your docker-compose.yml. So, lets continue...
  - label: 'Create package'
    command: package.sh
    env:
      BUILD_TYPE: Debug
      CURRENT_DIR: ${CURRENT_DIR}
      OS: centos7
    plugins:
      - ecr#v2.1.1: *ecr # login to ECR (Optional)
      - gencer/cache#v2.3.7: *cache # Cache will backup or restore here
      - docker-compose#v3.7.0: *centos7 # which is in docker-compose "working" directory.
    artifact_paths:
      - 'build/CMakeFiles/CMakeOutput.log'
      - 'build/*.AppImage'
      - 'build/*.rpm'
```

The only thing you need to be careful for the Docker and Docker Compose is UID's and GUID's. Basically, user mapping. If you have incorrect mapping you will end up with broken caches. Buildkite EC2 Plugin has no issues with this. Also see #32.

**Comment by miles-** [comment]
Thanks for the reply & the example @gencer. I was originally trying to use the [build option](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#build) from the docker-compose plugin rather than the `run` option, but I don't think it mounts the current working directory.

I'm now trying to use the docker-compose plugin with `run`. Here's what the step looks like:
```
- name: ':docker: build image'
  command: "echo $(pwd) && ls bundle/"
  plugins:
    gencer/cache#v2.4.9:
      id: ruby
      key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum 'Gemfile.lock' }}"
      restore-keys:
        - 'v1-cache-{{ id }}-{{ runner.os }}-'
        - 'v1-cache-{{ id }}-'
      compress: true
      compress-program: gzip
      backend: s3
      s3:
        bucket: cache-bucket
      paths:
        - 'bundle'
    docker-compose#v3.7.0:
      run: service
      config: docker-compose-buildkite.yml
```

When that step runs, the output of the command is:
```
/app
bin  build_info  bundler  cache  doc  extensions  gems	specifications
```

So the `/app/bundle` directory exists within the container, but the cache plugin isn't seeing it. It then uploads an empty tar.gz file to the S3 bucket.
```
Processing Post-Cache for ruby
[ruby] - 🔍 Locating source: v1-cache-ruby-Linux-checksum
[ruby] - 🔍 Locating cache: bundle
tar: bundle: Warning: Cannot stat: No such file or directory
upload: ./v1-cache-ruby-Linux-checksum.tar.gz to s3://cache-bucket/v1-cache-ruby-Linux-checksum.tar.gz
```

**Comment by gencer** [comment]
Is it possible to something in your docker-compose file cleans directory before Cache does post-cache step?

**Comment by gencer** [comment]
You know what, Let's found what's going on here. If you are willing to test, I can create a branch for you, so we can see what files are actually is in folder when Post Cache is started? 

P.S.: Sorry for the delay. I'll constantly look for this thread.

**Comment by miles-** [comment]
@gencer No problem re: the delay, I appreciate all of your help! I'm happy to test via a branch of the plugin :+1: . I'll double-check that nothing is clearing the directory before cache does the post-cache step as well.

**Comment by gencer** [comment]
Hey @miles-, Have you checked if anything is removed during post-cache?

**Comment by miles-** [comment]
Hey @gencer. From what I can tell, nothing is removing anything before or during the post-cache. The `docker-comopse build` step runs, then a `docker-compose run`, and then the ` /var/lib/buildkite-agent/plugins/github-com-gencer-cache-buildkite-plugin-v2-4-9/hooks/post-command` script. Is there a testing branch I can try out?

**Comment by gencer** [comment]
```yaml
- name: ':docker: build image'
  command: "echo $(pwd) && ls bundle/"
  plugins:
    gencer/cache#miles: # <-- here is your branch
      id: ruby
      key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum 'Gemfile.lock' }}"
      restore-keys:
        - 'v1-cache-{{ id }}-{{ runner.os }}-'
        - 'v1-cache-{{ id }}-'
      compress: true
      compress-program: gzip
      backend: s3
      s3:
        bucket: cache-bucket
      paths:
        - 'bundle'
    docker-compose#v3.7.0:
      run: service
      config: docker-compose-buildkite.yml
```

Let me know the output.
