### ISSUE TITLE
Use with docker build

### ISSUE THREAD

**Issue by ufou** [nienbo/cache-buildkite-plugin#41]
Hi,

I'm attempting to use this plugin alongside the docker plugin, though we are using docker to build the container, we then wish to cache the `node_modules` dir from docker, we're using `yarn.lock` checksum to trigger the cache, but `yarn.lock` is not found even though if you pull the image locally it exists, is this a limitation with this plugin to not work alongside a docker build?

I've tried having the cache plugin above or below the docker plugin with same results, eg:

```
  - id: "js-builder-container"
    label: ":docker: Build JS Builder Container"
    timeout_in_minutes: 10
    commands:
      - "docker buildx create --use --name ci || true"
      - "docker buildx build --ssh default --build-arg BUILDKITE_BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER} \
        --build-arg COMMIT_HASH=${BUILDKITE_COMMIT} \
        --cache-from=type=registry,ref=ci:js-builder-cache-master \
        --cache-from=type=registry,ref=ci:js-builder-cache-${BUILDKITE_BRANCH} \
        --cache-to=type=registry,ref=ci:js-builder-cache-${BUILDKITE_BRANCH},mode=max \
        -t ci:js-builder-${BUILDKITE_BUILD_NUMBER} \
        --progress=plain \
        --push -f .buildkite/Dockerfile-js-builder ."
    artifact_paths:
      - "website/js/schema.json"
      - "website/js/settings.json"
    plugins:
      - docker-login#v2.0.1:
           username: bob
      - gencer/cache#v2.4.10:
          id: js-builder
          key: "v1-cache-{{ id }}-{{ checksum 'yarn.lock' }}"
          compress: true
          restore-keys:
            - 'v1-cache-{{ id }}-'
          backend: s3
          paths:
            - 'node_modules'
```

excerpt from debug logs:
```
++++ TARGET=yarn.lock
--
  | +++++ find yarn.lock -type f -exec sha1sum '{}' ';'
  | +++++ sort -k 2
  | +++++ sha1sum
  | +++++ awk '{print $1}'
  | find: ‘yarn.lock’: No such file or directory
```

Inside the container:
```
root@61420a41d2d0:/usr/src/app/js# find yarn.lock -type f -exec sha1sum '{}' ';'
0673457b361e7b98ea37dae3163bb4498c01604d  yarn.lock
```

Not sure what else to try, any ideas?
Many thanks.
