### ISSUE TITLE
Multiple file paths for key caching

### ISSUE THREAD

**Issue by lewis785** [nienbo/cache-buildkite-plugin#45]
Is it possible to use multiple files for the checksum? I am trying to add caching to a repository that has multiple sub packages and would like the cache to update if any of the package-lock files were change.

Example:
```
node-cache: &node-cache
    id: node
    key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum 'package-lock.json' 'src/example-1/package-lock.json' 'src/example-2/package-lock.json' }}"
    restore-keys:
        - 'v1-cache-{{ id }}-{{ runner.os }}-'
        - 'v1-cache-{{ id }}-'
    paths:
        - node_modules
        - src/**/node_modules
```

The cache seems to still work but says that it is unable to find the files.

Result:
```
find: ‘package-lock.json src/example-1/package-lock.json src/example-2/package-lock.json ’: No such file or directory
```

**Comment by gencer** [comment]
At the moment, you can either;

- checksum a single file
- checksum a whole single folder (recursively)

Multiple files like you described in your example will not work that way. **But this can be implemented**.

**Comment by gencer** [comment]
Hey @lewis785,

I'm doing my own tests on my end. What do you think about the following approaches:

### Comma-separated:

```yaml
node-cache: &node-cache
    id: node
    key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum 'package-lock.json,src/example-1/package-lock.json,src/example-2/package-lock.json' }}"
```

### Glob-pattern:

```yaml
node-cache: &node-cache
    id: node
    key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum '**/package-lock.json' }}"
```

P.S.: This may be miss the main `/package-lock.json` and only include sub-directories.

### Key-based:

```yaml
node-cache: &node-cache
    id: node
    key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum }}" # if no data given, checksum key below will be used:
    checksum: # list of files to get cheksums
      - package-lock.json
      - **/package-lock.json # and glob pattern! or maybe full list of single files...
```

It seems `Key-based` is looking good and more fit to the structure.

Any ideas?
