### ISSUE TITLE
[FEATURE REQUEST] Ability to run a command before calculating cache key?

### ISSUE THREAD

**Issue by willhughes-au** [nienbo/cache-buildkite-plugin#47]
I have a situation where it would be useful to cache data, but the key needs to be a checksum of a file that isn't on the filesystem, yet. 

An arbitrary example: 

```
  - label: "Run Cached Step"
    command:
      - wget -O remote-config https://example.com
      - ./script-that-does-something.sh
    plugins:
      - gencer/cache#v2.4.10:
          key: "{{ id }}-{{ checksum 'remote-config' }}"
          paths:
            - .cache-dir
```

Running the wget command as a separate step won't work, as the file system gets cleaned, and even if there weren't, we run multiple agents. 

Would it be possible/make sense to have a pre-run-command argument that I could have, Or perhaps be able to invoke the plugin manually? 

Examples: 

```
  - label: "Run Cached Step"
    command:
      - ./script-that-does-something.sh
    plugins:
      - gencer/cache#v2.4.10:
          key: "{{ id }}-{{ checksum 'remote-config' }}"
          pre-restore-command: wget -O remote-config https://example.com
          paths:
            - .cache-dir
```
or perhaps: 

```
  - label: "Run Cached Step"
    command:
      - wget -O remote-config https://example.com
      - gencer-cache-restore
      - ./script-that-does-something.sh
    plugins:
      - gencer/cache#v2.4.10:
          key: "{{ id }}-{{ checksum 'remote-config' }}"
          defer_restore: true
          paths:
            - .cache-dir
```

This is probably a very niche/weird request.
