### ISSUE TITLE
Glob fails `**/node_modules: Warning: Cannot stat: No such file or directory`

### ISSUE THREAD

**Issue by mrjackdavis** [nienbo/cache-buildkite-plugin#49]
I'm trying to use ** glob in this plugin and I get the following error

Configuration:

```
   plugins:
      - gencer/cache#v2.4.10:
          id: node_modules
          backend: s3
          key: "v2-cache-{{ NODE_MODULES_ARTIFACT_HASH }}"
          restore-keys:
            - "v2-cache-{{ NODE_MODULES_ARTIFACT_HASH }}"
          compress: true
          s3:
            # bucket: "{{ BUILDKITE_ARTIFACT_BUCKET }}"
            bucket: "redacted"
          paths:
            - "node_modules"
            - "./workspaces/*/node_modules"
      - docker#v3.5.0:
          image: "{{ DOCKER_REPOSITORY }}/redacted:{{ PLATFORM_IMAGE_TAG_COMMIT }}"
          mount-checkout: true
```

Error:

```
[node_modules] - 🔍 Locating source: v2-cache-677a66f676e9203508bc6caf71f45d9e19cfe25a
[node_modules] - 🔍 Locating cache: node_modules ./workspaces/*/node_modules **/node_modules
tar: **/node_modules: Warning: Cannot stat: No such file or directory
```

<img width="799" alt="image" src="https://user-images.githubusercontent.com/1670700/177091463-9afa9edb-7fe9-4285-bd06-012e5218f6ca.png">

Any advice would be appreciated
