### ISSUE TITLE
[FEATURE REQUEST] Skip command if cache hit found

### ISSUE THREAD

**Issue by irphilli** [nienbo/cache-buildkite-plugin#51]
In the case for a command that is responsible for populating the cache, it would be helpful to go ahead and skip the command on a non-restore key cache hit. This can help optimize a flow if the command populating the cache takes some time (i.e. in a docker container, where the pull/startup takes time)

Something like:
```
steps:
  - label: Populate Cache
    command: ./populate_cache.sh
    plugins:
      - gencer/cache#v2.4.11:
        ...
        skip_command_on_cache_hit: true
```
