### ISSUE TITLE
[feature] Allow environment variables in bucket name

### ISSUE THREAD

**Issue by JP-Ellis** [nienbo/cache-buildkite-plugin#70]
I have a use case whereby I would like to allow a variable in the S3 bucket name. For example:

```yaml
steps:
  - label: Step 1
    env:
      ENVIRONMENT: dev
    plugins:
      - nienbo/cache#v2.4.15:
          backend: s3
          id: python-312
          key: v1-{{ id }}-{{ checksum "pyproject.toml" }}
          restore-keys:
            - v1-{{ id }}
          compress: true
          s3:
            bucket: s3-cache-$ENVIRONMENT
            save-cache: true
          paths:
            - .cache/pip
```

I have tried using `$ENVIRONMENT`, `$$ENVIRONMENT` as well as `{{ env.ENVIRONMENT }}`, but none of the options seem to work unfortunately.

Is this supported through some other means? Or if not supported, could this be added?
